### PR TITLE
feat: release v1.0.2

### PR DESCRIPTION
**Pull request by gikf**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

I think I got a hang of it, some observations:
- CodeRoad cli is mindful of local line endings in `TUTORIAL.md`, so even if they won't get changed in the actual file (because of git), they may be changed in the json generated by cli. Resulting in many changes from one line ending to another.
- When on version branch in VS Code it's a bit confusing at first to not be able to see what's in the folder because of `.vscode/settings.json`.
- Is there way to go to a specific step when testing? I've read about `CODEROAD_ADMIN_MODE` env variable, which should allow that, but that doesn't seem to work in the container. I've tried setting the variable at various steps - in `devcontainer.json` or after running the container, but despite of env variable being set, the ability to change step wasn't there after starting CodeRoad.
- When rebasing I was getting some intermediate errors, because of having some of the changing files open in the VS Code. It kind of surprised me that this was able to interfere. Keeping files closed when git is going through various commits is not an issue though.
- Some maybe helpful compares [v1.0.1 vs v1.0.2](https://github.com/gikf/learn-relational-databases-by-building-a-mario-database/compare/v1.0.1..v1.0.2), [1320.1@v1.0.1 vs 1320.1@v.1.0.2](https://github.com/gikf/learn-relational-databases-by-building-a-mario-database/compare/bd3c282c350e383db96b320ade01c4fc5eb5b3ed..9d175997ff599c57acae2932a9c42f6cd32e4409)

### CODE REVIEW

**Comment by moT01** [comment]
Curious why this change is needed @gikf?

The only thing I see is that the title of that step was used `yippee.wav`, and the instructions asked users to add `yipee.wav`. If that's the only reason, I would rather just change the title to `yipee.wav`, and leave the rest alone.

**Comment by gikf** [comment]
@moT01 Hmm, that might be more convenient, although test description would have it incorrect, but that might be visible just for few seconds. https://github.com/freeCodeCamp/learn-relational-databases-by-building-a-mario-database/blob/0a50407a633b56d64ae1541348162e62fdb39822/.freeCodeCamp/test/1320.test.js#L11

Generally I've picked `yippee.wav` after a search which spelling seem to be used in the Mario context.

I'm okay with whichever option you choose.

**Comment by moT01** [comment]
I'll take another look then - maybe we'll just go with this since it's ready to go 👍

**Review by moT01 — APPROVED** [review]
LGTM @gikf 🎉 You're awesome 🚀

**Pull request merged**
