### PR TITLE
fix: minor typo #1440.1

### PR DESCRIPTION
**Pull request by AndyTBurke**
"It look good." to "It looks good."

Checklist:

- [ x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Review by gikf — DISMISSED** [review]
This tutorial is using CodeRoad VS Code extension, specific guidelines how to contribute to them can be found on https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad. Changes in this PR require to follow parts referring to making changes on the `main` branch.

Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

Happy contributing.

**Comment by gikf** [comment]
Hey @AndyTBurke, did you have a chance to take a look at the linked docummentation?

**Comment by AndyTBurke** [comment]
> Hey @AndyTBurke, did you have a chance to take a look at the linked documentation?

I have done so now! Sorry for the delay (baby was sick with covid, then stomach flu, then pink eye - it has been a rough couple of weeks). I read through the contribution documentation, and hopefully I did everything correctly. the "coderoad build" command made changes to the tutorial,json that I admit I do not understand. So hopefully it is as it should be.

**Review by moT01 — APPROVED** [review]
LGTM @AndyTBurke 🎉 Thanks for contributing to freeCodeCamp 🎉

**Pull request merged**
